### PR TITLE
Declare an eyeglass version. Fixes #152

### LINKED ISSUE #152: Declare an eyeglass version
I get this message when compiling with sass
````
The following modules did not declare an eyeglass version:
[...]
breakpoint
[...]
````

Thank you and
With best regards

### PR DESCRIPTION
**Pull request by cienvaras**
https://github.com/at-import/breakpoint/issues/152

### CODE REVIEW

**Comment by markcarver** [comment]
Please commit!

```
The following modules did not declare an eyeglass version:
  breakpoint
Please add the following to the module's package.json:
  "eyeglass": { "needs": "^0.8.1" }
```

**Comment by philwareham** [comment]
Please can you merge this! And also on Singularity.gs, which has same issue.

**Comment by Snugug** [comment]
Updates coming in next two weeks.

**Comment by philwareham** [comment]
Great news, thanks!

**Pull request closed without merging**
